# Generated by Django 5.0.1 on 2024-02-06 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0003_userthemepreference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserThemePreference',
        ),
    ]
